### ISSUE TITLE
Convert to Object

### ISSUE THREAD

**Issue by willyanto** [kuma-giyomu/JSONParser#7]
Hi, sorry before, I ask in here. 
I successfully run your test code. But now how I can arrange every property and value into one object?
For example:
$activities = json_decode(file_get_contents($basePath . 'Activity.json'));

$activities will become object so I just call $activities->results or $activity->id.

**Comment by kuma-giyomu** [comment]
Hi,

you can't do that directly because it is not working like the `json_decode` function in PHP.
Essentially it is up to you to build your result object via the handler functions.

I'll work on a code sample for you to look at, but essentially it is a bad idea to do that on the whole document, since you'd only replicate the main issue: trying to load the complete document at once will cause PHP to run out of memory.

**Comment by willyanto** [comment]
Okay, thanks for your code sample.
Yes, my issue is OOM to decode 80MB json file. But I think it's very complicated if I process every result in handler. I need complete object to process them. This is my JSON sample
```javascript
{ "results" : [
   {
        "answer": {
            "__type": "Pointer",
            "className": "Answer",
            "objectId": "XjeZVtznqf"
        },
        "createdAt": "2014-11-21T09:25:49.440Z",
        "fromUser": {
            "__type": "Pointer",
            "className": "_User",
            "objectId": "Jv24WEyxVG"
        },
        "objectId": "aVEciEdwBk",
        "question": {
            "__type": "Pointer",
            "className": "Question",
            "objectId": "0Jdr0SbNOz"
        },
        "toUser": {
            "__type": "Pointer",
            "className": "_User",
            "objectId": "g15fuAausF"
        },
        "type": "like",
        "updatedAt": "2014-11-21T09:25:49.440Z"
    }
]
}
```
I need to separate the object. If the type "like" do action, If the type "follow user" do different action.

**Comment by kuma-giyomu** [comment]
The fact is you will have the same problem than when you're trying to use PHP's standard `json_decode`. You WILL run out of memory on sufficiently large files. So I do not think it is a good strategy to load the whole document.

This would work only if you try to parse small sub documents (your `results`' nodes in your case). Let's say you have an array of 80K elements of 1KB each (which would generate a total of 80MB of data).
I'd add make the parser ignore the top level structure, or possibly load some parameters of interest, then implement JSON document construction for the subset of interest (just concatenate the output).

A very naive way to do that would be to generate the JSON string and then feed it to `json_decode` instead of building the whole thing yourself and finally process the document on its own before discarding it. 
As the native function is backed by a C library, it will be way faster and efficient than any homegrown PHP code.

**Comment by willyanto** [comment]
Ok, I will try my best :)
Thanks you.
